language: php

sudo: required
dist: trusty

php:
  - 5.6

git:
  depth: 1

matrix:
  include:
    - php: 5.5
      install: sudo apt-get install php5-phalcon
    - php: 5.6
      install: sudo apt-get install php5-phalcon
    - php: 7.0
      env: ZEND_BACKEND="--backend=ZendEngine3"
      install: sudo apt-get install php7.0-phalcon

notifications:
  email:
    recipients:
      - kontakt@milankyncl.cz
    on_success: change
    on_failure: always